### ISSUE TITLE
Theory 270 not in theory.db 

### ISSUE THREAD

**Issue by flonigro** [HEP-PBSP/SIMUnet#57]
Theory 270 does not appear to be listed in theory.db. This leads to an error when running vp-setupfit as follows
```
validphys.theorydbutils.TheoryNotFoundInDatabase: ID 270 not found in database.
```
Note that, as stated in the documentation https://hep-pbsp.github.io/SIMUnet/sphinx/build/html/tutorials/Installation.html, I am using nnpdf4.0.5. Shouldn't we add theory 270 to theory.db?

**Comment by ElieHammou** [comment]
The fix has now been implemented. A simple `git pull` should be enough to fix the error now.
